import FormatBadge from "./FormatBadge";

const RecentExportsTable = () => {
  const data = [
    {
      name: "All Employees — Jan 2026",
      type: "Monthly",
      by: "Admin User",
      date: "Feb 1, 09:10",
      format: "Excel" as const,
    },
    {
      name: "Engineering Dept — Q4 2025",
      type: "Quarterly",
      by: "Admin User",
      date: "Jan 5, 14:22",
      format: "PDF" as const,
    },
    {
      name: "All Employees — Dec 2025",
      type: "Monthly",
      by: "Admin User",
      date: "Jan 2, 11:05",
      format: "CSV" as const,
    },
  ];

  return (
    <div className="bg-white rounded-2xl p-6 shadow-sm border mt-6">
      <h2 className="font-semibold text-lg mb-4">🕒 Recent Exports</h2>

      <table className="w-full text-sm">
        <thead className="text-gray-500 border-b">
          <tr>
            <th className="py-3 text-left">REPORT NAME</th>
            <th>TYPE</th>
            <th>GENERATED BY</th>
            <th>DATE</th>
            <th>FORMAT</th>
            <th>ACTION</th>
          </tr>
        </thead>

        <tbody>
          {data.map((row, index) => (
            <tr key={index} className="border-b">
              <td className="py-3">{row.name}</td>
              <td>{row.type}</td>
              <td>{row.by}</td>
              <td>{row.date}</td>
              <td>
                <FormatBadge format={row.format} />
              </td>
              <td>
                <button className="border px-4 py-1 rounded-lg bg-gray-50 text-sm">
                  ↓ Download
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default RecentExportsTable;